### ISSUE TITLE
Support API calls other than deleting

### ISSUE THREAD

**Issue by JLessinger** [JLessinger/fb_prune#16]
There may be graph API calls to, for example, report something. This may conflict with #15: one could either report the offending content or delete their own connection to it.

**Comment by wxiang54** [comment]
Haven't been able to find any reporting functionality on the graph API for the past hour :cry: 
These folks are probably right:
- http://stackoverflow.com/questions/35311163/is-there-an-api-for-facebook-or-facebook-page-to-report-spam-profiles-pages
- http://stackoverflow.com/questions/8575969/marking-fb-page-posts-as-spam

The only thing I've found vaguely related to reporting things is Insights:
https://developers.facebook.com/docs/graph-api/reference/v2.6/insights
This metric gives pages/apps the ability to see their page reports, including spam reports, specifically "page_negative_feedback_by_type / report_spam". However, I'm not sure how the data is represented and I don't think I can test because I don't have my own page or app. This probably won't help us either way, though.

I'll stick to working on deleting connections (or edges as I think they're called) to unwanted content, but I'll keep looking!

**Comment by JLessinger** [comment]
Ok, we'll do the best we can with #15. Closing this.
